name: vosk_stt
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  cached_network_image: ^3.4.1
  flutter_html: ^3.0.0
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  supabase_flutter: ^2.9.1
  speech_to_text: ^7.1.0
  permission_handler: ^12.0.1
  flutter_sound: ^9.28.0
  vosk_flutter: ^0.3.48
  path_provider: ^2.1.5
  device_info_plus: ^11.5.0
  archive: ^4.0.7
  mic_stream: ^0.7.2
  connectivity_plus: ^7.0.0
  web_socket_channel: ^3.0.3
  sqflite: ^2.4.2
  path: ^1.9.1

dependency_overrides:
  speech_to_text: 7.1.0
  permission_handler: ^12.0.1
  http: ^1.4.0
  archive: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/vosk-model-ar-mgb2-0.4.zip
    - assets/data/quran-metadata-surah-name.sqlite
    - assets/data/uthmani-15-lines.db
    - assets/data/uthmani.db
    - assets/data/

  fonts:
    - family: UthmanTN
      fonts:
        - asset: assets/fonts/UthmanTN_v2-0.ttf

    - family: Quran-Common
      fonts:
        - asset: assets\fonts\quran-common.ttf

    - family: Me_Quran
      fonts:
        - asset: assets\fonts\me_quran.ttf

    - family: surah-name-v2
      fonts:
        - asset: assets\fonts\surah-name-v2.ttf

    - family: KFGQPCUthmanicScriptHAFSRegular
      fonts:
        - asset: assets\fonts\KFGQPCUthmanicScriptHAFSRegular.otf